from __future__ import annotations

from typing import Any

import polars as pl

TABLE_KEYS: dict[str, list[str]] = {
    "posts": ["post_id"],
    "propagations": ["propagation_id"],
    "propagation_edges": ["propagation_id"],
    "comments": ["comment_id"],
    "comment_edges": ["comment_id"],
    "authors": ["author_id"],
    "media_refs": ["media_id"],
    "collection_runs": ["run_id"],
    "observed_sources": ["run_id", "container_source_id", "discovery_kind"],
    "match_hits": ["match_id"],
    "history_runs": ["history_run_id"],
    "history_windows": ["history_run_id", "window_id"],
    "history_item_index": ["history_run_id", "item_type", "item_id"],
    "history_narrative_clusters": ["history_run_id", "item_type", "cluster_id"],
    "history_cluster_memberships": ["history_run_id", "item_type", "item_id"],
    "history_stance_labels": ["history_run_id", "item_type", "item_id", "side_id"],
    "history_temporal_metrics": ["history_run_id", "window_id", "item_type", "cluster_id", "side_id", "metric_kind"],
    "history_coverage_gaps": ["history_run_id", "window_id", "child_run_id", "item_type", "item_id"],
}

TABLE_SCHEMAS: dict[str, dict[str, Any]] = {
    "posts": {
        "post_id": pl.String,
        "platform": pl.String,
        "source_id": pl.String,
        "source_kind": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "origin_permalink": pl.String,
        "propagation_kind": pl.String,
        "is_propagation": pl.Boolean,
        "container_source_id": pl.String,
        "container_source_name": pl.String,
        "container_source_url": pl.String,
        "container_source_type": pl.String,
        "discovery_kind": pl.String,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "raw_text": pl.String,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "shares": pl.Int64,
        "comments_count": pl.Int64,
        "views": pl.Int64,
        "forwards": pl.Int64,
        "reply_count": pl.Int64,
        "has_media": pl.Boolean,
        "media_type": pl.String,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "propagations": {
        "propagation_id": pl.String,
        "platform": pl.String,
        "source_id": pl.String,
        "source_kind": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "origin_permalink": pl.String,
        "propagation_kind": pl.String,
        "container_source_id": pl.String,
        "container_source_name": pl.String,
        "container_source_url": pl.String,
        "container_source_type": pl.String,
        "discovery_kind": pl.String,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "raw_text": pl.String,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "shares": pl.Int64,
        "comments_count": pl.Int64,
        "views": pl.Int64,
        "forwards": pl.Int64,
        "reply_count": pl.Int64,
        "has_media": pl.Boolean,
        "media_type": pl.String,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "propagation_edges": {
        "propagation_id": pl.String,
        "origin_post_id": pl.String,
        "origin_external_id": pl.String,
        "propagation_kind": pl.String,
        "platform": pl.String,
        "run_id": pl.String,
    },
    "comments": {
        "comment_id": pl.String,
        "platform": pl.String,
        "source_kind": pl.String,
        "parent_post_id": pl.String,
        "parent_entity_type": pl.String,
        "parent_entity_id": pl.String,
        "parent_comment_id": pl.String,
        "reply_to_message_id": pl.String,
        "thread_root_post_id": pl.String,
        "origin_post_id": pl.String,
        "container_source_id": pl.String,
        "container_source_name": pl.String,
        "container_source_url": pl.String,
        "container_source_type": pl.String,
        "discovery_kind": pl.String,
        "author_id": pl.String,
        "created_at": pl.String,
        "message": pl.String,
        "raw_text": pl.String,
        "depth": pl.Int64,
        "permalink": pl.String,
        "reactions": pl.Int64,
        "reaction_breakdown_json": pl.String,
        "source_collector": pl.String,
        "raw_path": pl.String,
        "run_id": pl.String,
    },
    "comment_edges": {
        "comment_id": pl.String,
        "parent_post_id": pl.String,
        "parent_entity_type": pl.String,
        "parent_entity_id": pl.String,
        "parent_comment_id": pl.String,
        "reply_to_message_id": pl.String,
        "thread_root_post_id": pl.String,
        "origin_post_id": pl.String,
        "depth": pl.Int64,
        "run_id": pl.String,
    },
    "authors": {
        "author_id": pl.String,
        "name": pl.String,
        "profile_url": pl.String,
        "source_collector": pl.String,
        "run_id": pl.String,
    },
    "media_refs": {
        "media_id": pl.String,
        "owner_post_id": pl.String,
        "media_type": pl.String,
        "title": pl.String,
        "url": pl.String,
        "preview_url": pl.String,
        "run_id": pl.String,
    },
    "collection_runs": {
        "run_id": pl.String,
        "collected_at": pl.String,
        "collector": pl.String,
        "mode": pl.String,
        "status": pl.String,
        "fallback_used": pl.Boolean,
        "request_signature": pl.String,
        "warning_count": pl.Int64,
        "warning_messages": pl.List(pl.String),
        "post_count": pl.Int64,
        "propagation_count": pl.Int64,
        "comment_count": pl.Int64,
        "platform": pl.String,
        "source_kind": pl.String,
        "source_id": pl.String,
        "source_name": pl.String,
        "source_type": pl.String,
        "discussion_linked": pl.Boolean,
        "filtered_service_message_count": pl.Int64,
        "source_run_count": pl.Int64,
        "source_run_ids": pl.List(pl.String),
    },
    "observed_sources": {
        "run_id": pl.String,
        "platform": pl.String,
        "container_source_id": pl.String,
        "container_source_name": pl.String,
        "container_source_url": pl.String,
        "container_source_type": pl.String,
        "discovery_kind": pl.String,
        "status": pl.String,
        "warning_count": pl.Int64,
        "source_collector": pl.String,
        "raw_path": pl.String,
    },
    "match_hits": {
        "match_id": pl.String,
        "run_id": pl.String,
        "item_type": pl.String,
        "item_id": pl.String,
        "match_kind": pl.String,
        "matched_value": pl.String,
        "platform": pl.String,
        "container_source_id": pl.String,
    },
    "history_runs": {
        "history_run_id": pl.String,
        "created_at": pl.String,
        "platform": pl.String,
        "source_kind": pl.String,
        "source_id": pl.String,
        "source_name": pl.String,
        "window": pl.String,
        "start": pl.String,
        "end": pl.String,
        "status": pl.String,
        "child_run_ids": pl.List(pl.String),
        "warning_count": pl.Int64,
        "warnings": pl.List(pl.String),
    },
    "history_windows": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "child_run_id": pl.String,
        "start": pl.String,
        "end": pl.String,
        "status": pl.String,
        "post_count": pl.Int64,
        "comment_count": pl.Int64,
        "propagation_count": pl.Int64,
        "match_hit_count": pl.Int64,
        "warning_count": pl.Int64,
        "coverage_gap_total": pl.Int64,
        "warnings": pl.List(pl.String),
    },
    "history_item_index": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "child_run_id": pl.String,
        "item_type": pl.String,
        "item_id": pl.String,
        "created_at": pl.String,
        "parent_post_id": pl.String,
        "parent_entity_type": pl.String,
        "parent_entity_id": pl.String,
        "origin_post_id": pl.String,
        "container_source_id": pl.String,
        "permalink": pl.String,
    },
    "history_narrative_clusters": {
        "history_run_id": pl.String,
        "item_type": pl.String,
        "cluster_id": pl.String,
        "label": pl.String,
        "description": pl.String,
        "top_keywords": pl.List(pl.String),
        "exemplar_ids": pl.List(pl.String),
    },
    "history_cluster_memberships": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "child_run_id": pl.String,
        "item_type": pl.String,
        "item_id": pl.String,
        "cluster_id": pl.String,
    },
    "history_stance_labels": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "child_run_id": pl.String,
        "item_type": pl.String,
        "item_id": pl.String,
        "side_id": pl.String,
        "label": pl.String,
        "confidence": pl.Float64,
        "model_name": pl.String,
    },
    "history_temporal_metrics": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "item_type": pl.String,
        "cluster_id": pl.String,
        "side_id": pl.String,
        "metric_kind": pl.String,
        "item_count": pl.Int64,
        "support_count": pl.Int64,
        "oppose_count": pl.Int64,
        "neutral_count": pl.Int64,
        "unclear_count": pl.Int64,
        "support_ratio": pl.Float64,
        "net_support": pl.Int64,
        "engagement_total": pl.Int64,
    },
    "history_coverage_gaps": {
        "history_run_id": pl.String,
        "window_id": pl.String,
        "child_run_id": pl.String,
        "item_type": pl.String,
        "item_id": pl.String,
        "visible_comment_count": pl.Int64,
        "extracted_comment_count": pl.Int64,
        "comment_gap": pl.Int64,
        "permalink": pl.String,
    },
}
